/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : HSM.h
**     Project     : Gateway_Reference_Ver1_Z4_0
**     Processor   : MPC5748G_176
**     Component   : security_pal
**     Version     : Component SDK_MPC574x_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-23, 16:08, # CodeGen: 1
**     Contents    :
**         SECURITY_Init                - status_t SECURITY_Init(security_instance_t instance, security_user_config_t *...
**         SECURITY_Deinit              - status_t SECURITY_Deinit(security_instance_t instance);
**         SECURITY_EncryptEcbBlocking  - status_t SECURITY_EncryptEcbBlocking(security_instance_t instance,...
**         SECURITY_EncryptEcb          - status_t SECURITY_EncryptEcb(security_instance_t instance, security_key_id_t...
**         SECURITY_DecryptEcbBlocking  - status_t SECURITY_DecryptEcbBlocking(security_instance_t instance,...
**         SECURITY_DecryptEcb          - status_t SECURITY_DecryptEcb(security_instance_t instance, security_key_id_t...
**         SECURITY_EncryptCbcBlocking  - status_t SECURITY_EncryptCbcBlocking(security_instance_t instance,...
**         SECURITY_EncryptCbc          - status_t SECURITY_EncryptCbc(security_instance_t instance, security_key_id_t...
**         SECURITY_DecryptCbcBlocking  - status_t SECURITY_DecryptCbcBlocking(security_instance_t instance,...
**         SECURITY_DecryptCbc          - status_t SECURITY_DecryptCbc(security_instance_t instance, security_key_id_t...
**         SECURITY_GenerateMacBlocking - status_t SECURITY_GenerateMacBlocking(security_instance_t instance,...
**         SECURITY_GenerateMac         - status_t SECURITY_GenerateMac(security_instance_t instance, security_key_id_t...
**         SECURITY_VerifyMacBlocking   - status_t SECURITY_VerifyMacBlocking(security_instance_t instance,...
**         SECURITY_VerifyMac           - status_t SECURITY_VerifyMac(security_instance_t instance, security_key_id_t...
**         SECURITY_LoadKey             - status_t SECURITY_LoadKey(security_instance_t instance, security_key_id_t...
**         SECURITY_LoadPlainKey        - status_t SECURITY_LoadPlainKey(security_instance_t instance const uint8_t *...
**         SECURITY_ExportRamKey        - status_t SECURITY_ExportRamKey(security_instance_t instance, uint8_t *m1,...
**         SECURITY_InitRng             - status_t SECURITY_InitRng(security_instance_t instance, uint32_t timeout);
**         SECURITY_ExtendSeed          - status_t SECURITY_ExtendSeed(security_instance_t instance, const uint8_t *...
**         SECURITY_GenerateRnd         - status_t SECURITY_GenerateRnd(security_instance_t instance, uint8_t *rnd,...
**         SECURITY_GetId               - status_t SECURITY_GetId(security_instance_t instance, const uint8_t *...
**         SECURITY_GenerateTrnd        - status_t SECURITY_GenerateTrnd(security_instance_t instance, uint8_t *trnd,...
**         SECURITY_SecureBoot          - status_t SECURITY_SecureBoot(security_instance_t instance, uint32_t...
**         SECURITY_BootFailure         - status_t SECURITY_BootFailure(security_instance_t instance, uint32_t timeout);
**         SECURITY_BootOk              - status_t SECURITY_BootOk(security_instance_t instance, uint32_t timeout);
**         SECURITY_BootDefine          - status_t SECURITY_BootDefine(security_instance_t instance, uint32_t bootSize,...
**         SECURITY_DbgChal             - status_t SECURITY_DbgChal(security_instance_t instance, uint8_t *challenge,...
**         SECURITY_DbgAuth             - status_t SECURITY_DbgAuth(security_instance_t instance, const uint8_t...
**         SECURITY_MPCompress          - status_t SECURITY_MPCompress(security_instance_t instance, const uint8_t...
**         SECURITY_GetAsyncCmdStatus   - status_t SECURITY_GetAsyncCmdStatus(security_instance_t instance);
**         SECURITY_CancelCommand       - status_t SECURITY_CancelCommand(security_instance_t instance);
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file HSM.h
** @version 01.00
*/
/*!
**  @addtogroup HSM_module HSM module documentation
**  @{
*/
#ifndef HSM_H
#define HSM_H
/* MODULE HSM. */

/* Include inherited beans */
#include "Cpu.h"

#endif
/* ifndef HSM_H */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
