################################################################################
# Automatically-generated file. Do not edit!
################################################################################

TODISASSEMBLE_SRCS_QUOTED := 
OBJ_SRCS_OS_FORMAT := 
S_UPPER_SRCS_QUOTED := 
TODISASSEMBLE_SRCS := 
O_SRCS_QUOTED := 
LD_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS := 
TODISASSEMBLE_SRCS_OS_FORMAT := 
O_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS_QUOTED := 
TOPREPROCESS_SRCS_OS_FORMAT := 
OSPT_SRCS := 
O_SRCS := 
ELF_SRCS := 
TOPREPROCESS_SRCS_QUOTED := 
S_SRCS_OS_FORMAT := 
C_SRCS_QUOTED := 
S_SRCS_QUOTED := 
ELF_SRCS_QUOTED := 
ELF_SRCS_OS_FORMAT := 
ASM_SRCS_OS_FORMAT := 
C_SRCS_OS_FORMAT := 
ASM_SRCS := 
S_UPPER_SRCS_OS_FORMAT := 
S_UPPER_SRCS := 
ASM_SRCS_QUOTED := 
OBJ_SRCS_QUOTED := 
LD_SRCS := 
OSPT_SRCS_QUOTED := 
LD_SRCS_QUOTED := 
OBJ_SRCS := 
S_SRCS := 
TOPREPROCESS_SRCS := 
C_SRCS := 
ASM_UPPER_SRCS_OS_FORMAT := 
OSPT_SRCS_OS_FORMAT := 
C_DEPS_OS_FORMAT := 
OBJS_OS_FORMAT := 
EXECUTABLES_OS_FORMAT := 
SECONDARY_SIZE_OS_FORMAT := 
C_DEPS_QUOTED := 
EXECUTABLES := 
OBJS := 
SECONDARY_SIZE := 
SECONDARY_SIZE_QUOTED := 
OBJS_QUOTED := 
EXECUTABLES_QUOTED := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Framework/dbg_console \
Framework/ecu \
Framework/gateway \
Framework/interfaces/can \
Framework/interfaces/ethernet \
Framework/interfaces/lin \
Framework/interfaces/sdhc \
Framework/pdu_router \
Framework/security \
Generated_Code \
Project_Settings/Startup_Code \
SDK/middleware/fatfs/common \
SDK/middleware/fatfs/rtc \
SDK/middleware/fatfs/source \
SDK/middleware/sdhc/fatfs \
SDK/middleware/sdhc/sd \
SDK/middleware/sdhc/usdhc \
SDK/platform/devices/MPC5748G/startup \
SDK/platform/devices \
SDK/platform/drivers/src/clock/MPC57xx \
SDK/platform/drivers/src/clock \
SDK/platform/drivers/src/edma \
SDK/platform/drivers/src/flexcan \
SDK/platform/drivers/src/hsm \
SDK/platform/drivers/src/interrupt \
SDK/platform/drivers/src/linflexd \
SDK/platform/drivers/src/pins \
SDK/platform/drivers/src/rtc_c55 \
SDK/platform/drivers/src/usdhc \
SDK/platform/pal/can/src \
SDK/platform/pal/security/src \
SDK/platform/pal/uart/src \
SDK/rtos/FreeRTOS_C55/Source \
SDK/rtos/FreeRTOS_C55/Source/portable/GCC/PowerPC_Z4 \
SDK/rtos/FreeRTOS_C55/Source/portable/MemMang \
SDK/rtos/osif \
Sources \
Sources/tables \

