/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : CAN2.c
**     Project     : Gateway_Reference
**     Processor   : MPC5748G_176
**     Component   : can_pal
**     Version     : Component SDK_MPC574x_03, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_03
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-13, 20:18, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file CAN2.c
** @version 01.00
*/
/*!
**  @addtogroup CAN2_module CAN2 module documentation
**  @{
*/
#include "CAN2.h"

const can_user_config_t CAN2_Config0 = {
    .maxBuffNum = 2U,
    .mode = CAN_NORMAL_MODE,
    .enableFD = true,
    .payloadSize = CAN_PAYLOAD_SIZE_64,
    .nominalBitrate = {
        .propSeg = 7,
        .phaseSeg1 = 5,
        .phaseSeg2 = 4,
        .preDivider = 3,
        .rJumpwidth = 3
    },
    .dataBitrate = {
        .propSeg = 7,
        .phaseSeg1 = 5,
        .phaseSeg2 = 5,
        .preDivider = 0,
        .rJumpwidth = 2
    },
    .extension = NULL,
};
/* END CAN2. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
