/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : lin_0.h
**     Project     : Gateway_Reference
**     Processor   : MPC5748G_176
**     Component   : linflexd_uart
**     Version     : Component SDK_MPC574x_03, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_03
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-13, 20:18, # CodeGen: 0
**     Abstract    :
**
**     Contents    :
**         LINFLEXD_UART_DRV_SetBaudRate          - status_t LINFLEXD_UART_DRV_SetBaudRate(uint32_t instance,uint32_t baudrate);
**         LINFLEXD_UART_DRV_GetBaudRate          - status_t LINFLEXD_UART_DRV_GetBaudRate(uint32_t instance,uint32_t * baudrate);
**         LINFLEXD_UART_DRV_Init                 - status_t LINFLEXD_UART_DRV_Init(uint32_t instance,linflexd_uart_state_t *...
**         LINFLEXD_UART_DRV_Deinit               - status_t LINFLEXD_UART_DRV_Deinit(uint32_t instance);
**         LINFLEXD_UART_DRV_InstallRxCallback    - linflexd_uart_callback_t LINFLEXD_UART_DRV_InstallRxCallback(uint32_t...
**         LINFLEXD_UART_DRV_InstallTxCallback    - linflexd_uart_callback_t LINFLEXD_UART_DRV_InstallTxCallback(uint32_t...
**         LINFLEXD_UART_DRV_InstallErrorCallback - linflexd_uart_callback_t LINFLEXD_UART_DRV_InstallErrorCallback(uint32_t...
**         LINFLEXD_UART_DRV_SendDataBlocking     - status_t LINFLEXD_UART_DRV_SendDataBlocking(uint32_t instance,const uint8 *...
**         LINFLEXD_UART_DRV_SendData             - status_t LINFLEXD_UART_DRV_SendData(uint32_t instance,const uint8 *...
**         LINFLEXD_UART_DRV_GetTransmitStatus    - status_t LINFLEXD_UART_DRV_GetTransmitStatus(uint32_t instance,uint32_t *...
**         LINFLEXD_UART_DRV_AbortSendingData     - status_t LINFLEXD_UART_DRV_AbortSendingData(uint32_t instance);
**         LINFLEXD_UART_DRV_ReceiveDataBlocking  - status_t LINFLEXD_UART_DRV_ReceiveDataBlocking(uint32_t instance,uint8 *...
**         LINFLEXD_UART_DRV_ReceiveData          - status_t LINFLEXD_UART_DRV_ReceiveData(uint32_t instance,uint8 *...
**         LINFLEXD_UART_DRV_GetReceiveStatus     - status_t LINFLEXD_UART_DRV_GetReceiveStatus(uint32_t instance,uint32_t *...
**         LINFLEXD_UART_DRV_AbortReceivingData   - status_t LINFLEXD_UART_DRV_AbortReceivingData(uint32_t instance);
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file lin_0.h
** @version 01.00
** @brief
**
*/
/*!
**  @addtogroup lin_0_module lin_0 module documentation
**  @{
*/
#ifndef lin_0_H
#define lin_0_H
/* MODULE lin_0. */
/* Include inherited beans */
#include "clockMan1.h"
#include "dmaController1.h"
#include "Cpu.h"
#include "linflexd_uart_driver.h"

/*! @brief Device instance number */
#define INST_LIN_0 (0U)

/*! Driver state structure */
extern linflexd_uart_state_t lin_0_State;

/*! @brief Configuration declaration */
extern linflexd_uart_user_config_t lin_0_InitConfig0;

#endif  /* ifndef lin_0_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
