/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : usdhc1.c
**     Project     : Gateway_Reference
**     Processor   : MPC5748G_176
**     Component   : usdhc
**     Version     : Component SDK_MPC574x_03, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_03
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-13, 20:18, # CodeGen: 0
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file usdhc1.c
** @version 01.00
*/
/*!
**  @addtogroup usdhc1_module usdhc1 module documentation
**  @{
*/
#include "usdhc1.h"

/* uSDHC state structure */
usdhc_state_t usdhc1_State;

uint8_t usdhc1_admaTable0[32767];

/* uSDHC User Configurations */
usdhc_config_t usdhc1_Config0 = {
    .cardDetectDat3  = true,
    .endianMode      = uSDHC_ENDIAN_MODE_LITTLE,
    .dmaMode         = uSDHC_DMA_MODE_ADMA2,
    .admaTable       = usdhc1_admaTable0,
    .admaTableSize   = 32767U
};

/* END usdhc1. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
