/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : adc_pal1.c
**     Project     : ECU_Engine_01_Z4_0
**     Processor   : MPC5748G_324
**     Component   : adc_pal
**     Version     : Component SDK_MPC574x_04, Driver 01.00, CPU db: 3.00.000
**     Repository  : SDK_MPC574x_04
**     Compiler    : GNU C Compiler
**     Date/Time   : 2018-04-27, 09:23, # CodeGen: 4
**
**     Copyright 1997 - 2015 Freescale Semiconductor, Inc.
**     Copyright 2016-2017 NXP
**     All Rights Reserved.
**     
**     THIS SOFTWARE IS PROVIDED BY NXP "AS IS" AND ANY EXPRESSED OR
**     IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
**     OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
**     IN NO EVENT SHALL NXP OR ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
**     INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
**     SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
**     HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
**     STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
**     IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
**     THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file adc_pal1.c
** @version 01.00
*/
/*!
**  @addtogroup adc_pal1_module adc_pal1 module documentation
**  @{
*/

/* MODULE adc_pal1. */

/**
 * @page misra_violations MISRA-C:2012 violations
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.7, External variable could be made static.
 * The external variables will be used in other source files, with the same initialized values.
 *
 * @section [global]
 * Violates MISRA 2012 Advisory Rule 8.9, Could define variable at block scope.
 * The external variables will be used in other source files, with the same initialized values.
 */

#include <stddef.h>
#include "adc_pal1.h"

/*! @brief PAL instance information */

const adc_instance_t adc_pal1_instance = { ADC_INST_TYPE_ADC_MPC574xC_G_R, 0u };

/*! @brief Configuration 0 declaration */

static extension_adc_mpc574xc_g_r_t adc_pal1_Extension0 = {
    .clkSelect          = ADC_CLK_HALF_BUS,
    .refSelect          = ADC_REF_VREFH,
    .autoClockOff       = false
};

const adc_config_t adc_pal1_InitConfig0 = {
    .sampleTicks        = 50,
    .numGroups          = 1,
    .groupConfigArray   = adc_pal1_GroupArray0,
    .extension          = &adc_pal1_Extension0
};

const adc_group_config_t adc_pal1_GroupArray0[1u] = {
    /* Conversion group 0 */
    {
        adc_pal1_ChansArray00,     /* inputChannelArray */
        adc_pal1_Results00,        /* resultBuffer */
        1,     /* numChannels */
        1,     /* numSetsResultBuffer */
        false,        /* hwTriggerSupport */
        0u,     /* triggerSource */
        ADC_DELAY_TYPE_NO_DELAY,      /* delayType */
        NULL,       /* delayArray */
        false,     /* continuousConvEn */
        adc_pal1_callback00,       /* callback */
        NULL        /* callbackUserData */
    },
};

adc_input_chan_t adc_pal1_ChansArray00[1u] = {
    ADC_CHAN_MAP(1u, 9u),
};
uint16_t adc_pal1_Results00[(1u) * (1u)];


/* END adc_pal1. */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.1 [05.21]
**     for the NXP C55 series of microcontrollers.
**
** ###################################################################
*/
